const countries = [
    { value: 'AF', label: 'Afghanistan', flag: 'af' },
    { value: 'AX', label: 'Åland Islands', flag: 'ax' },
    { value: 'AL', label: 'Albania', flag: 'al' },
    { value: 'DZ', label: 'Algeria', flag: 'dz' },
    { value: 'AS', label: 'American Samoa', flag: 'as' },
    { value: 'AD', label: 'Andorra', flag: 'ad' },
    { value: 'AO', label: 'Angola', flag: 'ao' },
    { value: 'AI', label: 'Anguilla', flag: 'ai' },
    { value: 'AQ', label: 'Antarctica', flag: 'aq' },
    { value: 'AG', label: 'Antigua and Barbuda', flag: 'ag' },
    { value: 'AR', label: 'Argentina', flag: 'ar' },
    { value: 'AM', label: 'Armenia', flag: 'am' },
    { value: 'AW', label: 'Aruba', flag: 'aw' },
    { value: 'AU', label: 'Australia', flag: 'au' },
    { value: 'AT', label: 'Austria', flag: 'at' },
    { value: 'AZ', label: 'Azerbaijan', flag: 'az' },
    { value: 'BS', label: 'Bahamas', flag: 'bs' },
    { value: 'BH', label: 'Bahrain', flag: 'bh' },
    { value: 'BD', label: 'Bangladesh', flag: 'bd' },
    { value: 'BB', label: 'Barbados', flag: 'bb' },
    { value: 'BY', label: 'Belarus', flag: 'by' },
    { value: 'BE', label: 'Belgium', flag: 'be' },
    { value: 'BZ', label: 'Belize', flag: 'bz' },
    { value: 'BJ', label: 'Benin', flag: 'bj' },
    { value: 'BM', label: 'Bermuda', flag: 'bm' },
    { value: 'BT', label: 'Bhutan', flag: 'bt' },
    { value: 'BO', label: 'Bolivia (Plurinational State of)', flag: 'bo' },
    { value: 'BQ', label: 'Bonaire, Sint Eustatius and Saba', flag: 'bq' },
    { value: 'BA', label: 'Bosnia and Herzegovina', flag: 'ba' },
    { value: 'BW', label: 'Botswana', flag: 'bw' },
    { value: 'BV', label: 'Bouvet Island', flag: 'bv' },
    { value: 'BR', label: 'Brazil', flag: 'br' },
    { value: 'IO', label: 'British Indian Ocean Territory', flag: 'io' },
    { value: 'BN', label: 'Brunei Darussalam', flag: 'bn' },
    { value: 'BG', label: 'Bulgaria', flag: 'bg' },
    { value: 'BF', label: 'Burkina Faso', flag: 'bf'}
]

export default countries;
